import Head from 'next/head'

import { css } from '@emotion/react';

import Layout from '../components/layout';

const homeCss = css({});

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </Layout>
  );
};

export default Home;