import { css } from '@emotion/react';
import Head from 'next/head'

const homeCss = {
};


export default function Home() {
  return (
    <div css={homeCss.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button css={homeCss.button}>sssss</button>
    </div>
  )
}
