import Head from 'next/head'

import { css } from '@emotion/react';

const homeCss = css({});

const Home = () => {
  return (
    <div css={homeCss}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  );
};

export default Home;